language: java
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
    sudo: false
  - os: osx
    osx_image: xcode7.3
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update        ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/libexec/java_home -V; fi
install:
- git clone -n https://github.com/ClearVolume/scenery.git --depth 1
- cd scenery/
- git checkout HEAD jars/openvr-0.1.jar
- cd ..
script:
- mvn initialize
- mvn compile
after_success:
- chmod a+x threedviewer_deploy.sh
- bash threedviewer_deploy.sh
env:
  global:
  - secure: Qd7A3JoS+oJAiWmMdImXVQ77suLdOv5QDop4RqPEwlbr0wWvbN5WzMOwESY2124kmrmtP8ShCfN1+bUwpyfYM2aLGCqlfoXw425h0z5W3QONRt/VhjveFXeO9qMamfS11QObtNC3x3FzU/fUuojPMZon/iDFT+vZENjKQEoJ7+8LzbFz9Mv1lzRtr+DZmCuhAYsdXmCmKbBKVOJo+Iv7dqzKbWFMmQOcvLWTCtW1VopfSKi96Pl1SP18SslK1/IWleFNBgsdn89NQLJE+jK8CL8Lmg+U3i570cQO5MD+qKQ9NxPmwIeXdnBVR7owcdAkuTiDztD5lk6xeiePqD22x95SaXW4af45JjoFgedEIe1LVRjED905KvxmTZohFigChTJMRY48gK/1R8kf0rikBLu/NfcYvutHYySt+zmWq0HaoMVykhxMnTeULO+3b3mY/c2Bipa4zWROnsJklefX0FQN46h1ll9Q7AZN1e4PkINcRtut/mCt8cNiQJv+Wlzc/HJ8ypokR96OKIVTqjRDkK59wHthoFizVreA0TssmRE7ZFGtesKQnE+CrL+bHeaj/Z7PWMcYP6T95E4/Jq7K5kWmOjLtT8dxjl9S0y3WVpgbI/oAKFblxAOGAs0Xy4+CAZCwCBALg55pthYoDFk0FECv5xYNlsKom4y2UuhNH34=
  - secure: BKqBUUIr10zjaS/oLLvn+VlVu9XXxZsZgjyN1R1KLqZWnKfNrbwF7wCyXHx8HX0yK71BaDsLh763TsPQEl/VcL/Fq9YUXjx5471ufWQ45KX3ks8YUOxyvXkCEkm5NQDCsxHIbe3xMXXz0+fDfPICYMUXuNILmSB+jTnikWeRGPIb2+8ieA4Hq0flO8lLYQygfex6CmJbfZZtyXfEZcms7xT8jLDVSODS7HhtFa55rc4w+QRvgCA7DVC9m1TNCDBPJfDUXXP1Lm0YqveDvOOUAiURIkS7hy6gqo5zNg081vikRrCRUSvYG6DnW6KLNJk3o4AGmBQyhHiLF5WCSWrghMI+1FaTIuV1tvxn7oROWc+YqajchqF6ZBMslsFNAIebzSei/CerHyqszIFJ0pu1ucg3jA4xLo/CGrWdu8QuoOuKoNnOuTYN+vsMS7Xh9MX7QY34j/hTYx9fNCLHQ0X4EEt1viVWK6bTiO5WhVVT0nTDHnAwHrY6njupj7/YxOVsPvy7fngkuvpjQm69NRgbjJdSu1knPDoxZvMWA90ObuSQ5nXTxEAVvc99lZoMVoFNlX6EmdtTWXm/KTOHSyQmxLOX2GNdXPg6OfUiQ8bTEwnTp5lGGL7Oo6TjPoATkGg1ihio+l7ksJ1S7JcYEg3NoLIt9gqGF1dzwTxK4Zaj4U4=
  - secure: DdLSgTFaraEn63qUdwf1pOK6HCyZjrBmCvCFqA6GhY9oQTYd17ZC36LN4LLy5Z1uq/8aZlUHp9nfpfILd/OXFpGguEsJGmN59mvs+7uD/ytYLLP5lq2yw0um37S+fLn94/+Twv6owTdqVxvwX6ZWGENg5d8RyZJVLxXijzVLvuZy4a9hOoPn6jA1tjQ9iosv52zASBvhwMosVRp+BL/c62pdiYbDZUTWnpO5o5qvh3nvzsGDJ7n61JAG1BZqgl4ym3tvoinwkUY1kur2HOgDGkhAOe1Re3VTDYXAK9X6owmCHUwj/OWAOFLAWENmYc1uZ5MIc+Rf62X2rMvQzx2I/XGxWhy2/xMvXI88fsHDKb+AySf5r5ZxeVAbXIIbpSAiHtR5N9iZjp7p3t9PKqmSBj3YbV+NxBWFsPDJ4K4p7eSC4cx1AAzxOQCh7phDSXGDueZvrnaoHFxnXvW3xZ98kGvbJ5I9qsRFLkK7mht2oU4dQpJGdXZ8geL7du0RXpx8mGxTr+tt43FcMLe16i2LCKIyfcQCovYGVy+KLYBba6vSRCiG6HygJQfJ7kG5AQkeINp7B1d0AUPM855AeUumJpw+TKL54JT1XYZH3EyYbjT+DeklC61DvtkfMbYfIMeMmMiesbhWZvg7CwO749jvWKJB5x2oIMZVhMszQ40q4K0=
